<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Notifications\Notifiable;

class Order extends Model
{
    use HasFactory, Notifiable;

    protected $table = 'orders';

    // Fields to be generated by the factory
    protected $fillable = [
        'product',
        'quantity',
        'total',
        'user_id',
    ];
}
